from LinkedList import LinkedList, Node

def main():
    print("-----TEST 1-----")
    linkl = LinkedList()
    linkl.push_front(45)
    linkl.push_front(39)
    linkl.push_front(10)
    linkl.push_front(98)
    linkl.push_front(6)
    print(linkl)
    print("Length: ", linkl.length())
    print("Empty: ", linkl.is_empty())
    print("Front: ", linkl.front_value())
    print("Back: ", linkl.back_value())

    print("\n-----TEST 2-----")
    ll2 = LinkedList()
    ll2.push_back(45)
    ll2.push_back(39)
    ll2.push_back(10)
    ll2.push_back(98)
    ll2.push_back(6)
    print(ll2)
    print("Length: ", ll2.length())
    print("Empty: ", ll2.is_empty())
    print("Front: ", ll2.front_value())
    print("Back: ", ll2.back_value())

    print("\n-----TEST 3-----")
    ll3 = LinkedList()
    ll3.push_back(47)
    ll3.push_front(39)
    ll3.push_back(21)
    ll3.push_front(58)
    ll3.push_back(32)
    ll3.push_front(94)
    ll3.push_back(16)
    ll3.push_front(77)
    ll3.push_back(56)
    ll3.push_front(21)
    ll3.push_back(4)
    ll3.push_front(79)
    print(ll3)
    print("Count of 21: ", ll3.find(21))
    print("Count of 21: ", ll3.count(21))
    print("Count of 94: ", ll3.find(94))
    print("Count of 94: ", ll3.count(94))
    print("Count of 43: ", ll3.find(43))
    print("Count of 43: ", ll3.count(43))

    print("\n-----TEST 4-----")
    print("Original: ", ll3)
    ll3.pop_front()
    print("Del Front: ", ll3)
    ll3.pop_front()
    print("Del Front: ", ll3)
    ll3.pop_back()
    print("Del Back:  ", ll3)
    ll3.pop_back()
    print("Del Back:  ", ll3)

    # Make sure to add your own tests and thoroughly test all functions
    # You will not be turning in this file, so change as much as you want!

main()